
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8
    username: payment
    password: payment
server:
  servlet:
    context-path: /batch
  port: 9994
  
feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000 
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS
  
